### ISSUE TITLE
Stop using origin netty interfaces directly

### ISSUE THREAD

**Issue by alalag1** [esastack/esa-restlight#12]
We are using the netty interfaces(or classes) in interfaces that would be used by the end-user such as `io.netty.buffer.ByteBuf`, `io.netty.handler.codec.http.HttpHeaders`, `io.netty.handler.codec.http.cookie.Cookie` and so on...
And this time we want to replace these interfaces(or classes) with our own interfaces(or classes) such as `esa.commons.netty.core.Buffer`, `esa.commons.http.HttpHeaders`, `esa.commons.http.Cookie` and so on...

> Try to prevent the end-user from using origin netty interfaces directly, and let end-user use our own interfaces(or classes).

**Comment by Mkabaka** [comment]
`HttpResponseStatus` should be replaced.
