### ISSUE TITLE
The response body param wrong

### ISSUE THREAD

**Issue by oppo-chenglu** [esastack/esa-restlight#136]
### Expected behavior
```json
{"useName": null, "iName": "xxx"}
```

### Actual behavior
![image](https://user-images.githubusercontent.com/102855655/161922890-5b64dea0-287c-4c65-a5db-693dddf43a71.png)

### Steps to reproduce
use entity
```java
    class Hello {
        String iName;

        String userName;
    }
```

### Env
- Restlight version: 1.0.0-SNAPSHOT
- JVM version: jdk11
- OS:window 10

**Comment by LCDZhao-Z** [comment]
We use Jackson to serialize by default. Jackson serializes the iName to iname by default. Users can configure it according to their own needs or use other serialization.
