### ISSUE TITLE
Can we support not provide the annotation like @RequestParam in controller.

### ISSUE THREAD

**Issue by oppo-chenglu** [esastack/esa-restlight#142]
### Expected behavior
not contains the `@RequestParam`, the application still start normally.

### Actual behavior
throw exception
```
Caused by: java.lang.IllegalArgumentException: There is no suitable resolver to handle param: [MethodParam: io.esastack.demo.controller.HelloController=>hello@name]
```

### Env
- Restlight version: 1.0.0-SNAPSHOT
- JVM version: 1.8
- OS:windows 10

**Comment by alalag1** [comment]
We are more inclined to follow the JAX-RS standard, which is more clear in the definition of annotation usage and does not provide similar usage you mentioned
