### ISSUE TITLE
customize `ExceptionResolver` can't work.

### ISSUE THREAD

**Issue by brotherlu-xcq** [esastack/esa-restlight#146]
### Expected behavior
can resolve the exception.

### Actual behavior
does not work.

### Steps to reproduce
1. add customize `ExceptionResolver` .
```java
@Component
public class GlobalExceptionResolver implements ExceptionResolver<RuntimeException> {
    @Override
    public CompletionStage<Void> handleException(RequestContext context, RuntimeException exception) {
        context.response().status(HttpStatus.FORBIDDEN.code());
        context.response().entity(exception.getMessage());
        return CompletableFuture.completedFuture(null);
    }
}
```
2.add exception controller
```java
    @GetMapping("get/exception")
    public void exception() {
        throw new RuntimeException("Forbidden");
    }
```

### Env
- Restlight version: 1.0.0-SNAPSHOT
- JVM version: 1.8
- OS:Windows 10

**Comment by LCDZhao-Z** [comment]
I haven't encountered this problem with the same environment and the same code.

**Comment by LCDZhao-Z** [comment]
I haven't encountered this problem with the same environment and the same code.
