### ISSUE TITLE
better to use junit5

### ISSUE THREAD

**Issue by alalag1** [esastack/esa-restlight#165]
### Expected behavior

better to use Junit5 like other  modules

### Actual behavior

https://github.com/esastack/esa-restlight/blob/4f2cb402ad7e794d8ecec46833a6dd90e7532a77/restlight-integration-test/pom.xml#L24

### Env
Restlight version: 1.0.0-SNAPSHOT
JVM version: 1.8
OS:Windows 10

**Comment by brotherlu-xcq** [comment]
ok, I will resolve it.
