### ISSUE TITLE
wrong use of  `CompletableFuture`?

### ISSUE THREAD

**Issue by alalag1** [esastack/esa-restlight#177]
https://github.com/esastack/esa-restlight/blob/4f2cb402ad7e794d8ecec46833a6dd90e7532a77/restlight-springmvc-provider/src/main/java/io/esastack/restlight/springmvc/spi/core/SpringMvcExceptionHandlerFactory.java#L47-L67

why create a new `CompletableFuture` instead of using `cf.compose(xx)` or just return the passed `CompletableFuture` handle?

### Env
- Restlight version: 1.0.0-SNAPSHOT

**Comment by LCDZhao-Z** [comment]
We need to process the exception when the stage is completed exceptionally. So using cf.compose(xx) or just returning the passed CompletableFuture can,t meet our needs.
